config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users
  resources :tickets, only: [:show, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tickets#index'

  resources :tickets do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    belongs_to :ticket

    validates :card_number, presence: true, format: { with: /\A\d+\z/, message: "Only numbers allowed" }
    validates_length_of :card_number, :maximum => 16, :minimum => 16
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_many :users, through: :bookings
    has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :tickets, through: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.where(user_id: current_user.id)
    @bookings_detail = @bookings.joins(:ticket).order('departure')
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { redirect_to new_booking_path, notice: 'Invalid card number. Must be 16 numeric characters'}
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:card_number, :user_id, :ticket_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all.order('departure')
    @bookings = Booking.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:company, :departure, :from, :to, :num_max)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper

    def get_hours time_diff
        time_diff = time_diff.round.abs
        hours = time_diff / 3600
        hours
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
<% if booking.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

    <ul>
        <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :card_number , class: "form-field"%>
    <%= form.text_field :card_number %>
</div>

<div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field">
    <%= form.hidden_field :ticket_id, value: params[:ticket_id] %>
</div>

<div class="actions">
    <%= form.submit%>
</div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h2><%="#{current_user.email[0,current_user.email.index('@')]}'s bookings"  %></h2>

<table>
    <thead>
        <tr>
            <th>Company</th>
            <th>From</th>
            <th>To</th>
            <th>Departure</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @bookings_detail.each do |booking| %>
        <% if (booking.ticket.departure-2.hours) > DateTime.now %>
        <tr>
            <td><%= booking.ticket.company %></td>
            <td><%= booking.ticket.from %></td>
            <td><%= booking.ticket.to %></td>
            <td><%= booking.ticket.departure.to_formatted_s(:long)    %></td>
            <% if get_hours((booking.ticket.departure-2.hours)-DateTime.now).nil? || get_hours((booking.ticket.departure-2.hours)-DateTime.now)<=0 %>
            <td> Too late to cancel </td>
            <% else %>
            <td><%= link_to 'Cancel', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-cancel"%></td>
            <% end %>
        </tr>
        <% end %>
        <% end %>
    </tbody>
</table>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking , class: "form"%>

app/views/bookings/show.html.erb
<p>
  <strong>Card number:</strong>
  <%= @booking.card_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @booking.ticket_id %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= link_to 'Back to tickets', root_path , class: "btn btn-passive"%>
</body>

</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.datetime_select :departure %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="field">
    <%= form.label :num_max %>
    <%= form.number_field :num_max %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
    <div class="container">
        <div class="nav">
            <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete , class: 'btn btn-passive'%>
            <%= link_to "My Tickets", bookings_path, class: 'btn btn-passive' %>
            <strong class="icon-user"><%=current_user.email[0,current_user.email.index('@')] %></strong>
            <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-passive'%>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-action" %>
            <% end %>
        </div>
        <h1>SKK Bookings</h1>

        <table class="layout display responsive-table">
            <thead>
                <tr>
                    <th class="table upper left">Company</th>
                    <th>Departure</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Available tickets</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @tickets.each do |ticket| %>
                <% if (ticket.departure-2.hours)>DateTime.now  %>
                <tr>
                    <td><%= ticket.company %></td>
                    <td><%= ticket.departure.to_formatted_s(:long)    %></td>
                    <td><%= ticket.from %></td>
                    <td><%= ticket.to %></td>
                    <% num_available =  ticket.num_max - @bookings.where(ticket_id: ticket.id).length %>
                    <td><%= num_available  %></td>
                    <% if num_available > 0 %>
                    <td><%= link_to 'Buy', new_ticket_booking_path(ticket), class: "btn btn-buy" %></td>
                    <% else  %>
                    <td>No more available tickets</td>
                    <% end %>
                </tr>
                <%end%>
                <% end %>
            </tbody>
        </table>
    </div>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back to tickets', root_path %>

app/views/tickets/show.html.erb
<p>
  <strong>Company:</strong>
  <%= @ticket.company %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @ticket.departure %>
</p>

<p>
  <strong>From:</strong>
  <%= @ticket.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @ticket.to %>
</p>

<%= link_to 'Back to tickets', root_path %>